name: Compile LaTeX Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: islandoftex/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        # Оставляем -outdir=build, чтобы не мусорить в корне
        run: |
          latexmk -pdf -shell-escape -outdir=build main.tex

      - name: Move PDF to root
        # Копируем файл из папки build в текущую папку (корень)
        run: cp build/main.pdf ./main.pdf

      - name: Upload PDF report
        uses: actions/upload-artifact@v4
        with:
          name: lab-report
          # Теперь путь ведет на файл в корне
          path: main.pdf